"""empty message

Revision ID: 1e29574d71d0
Revises: 
Create Date: 2023-03-31 06:00:46.730074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e29574d71d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betreff', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('termin', sa.String(length=15), nullable=True),
    sa.Column('firma', sa.String(length=20), nullable=True),
    sa.Column('projekt', sa.String(length=20), nullable=True),
    sa.Column('sammelaufgabe', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
